language: cpp
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"
    - os: osx
      env:
        - MATRIX_EVAL="export CC=clang && export CXX=clang++"
        - CXX_FLAGS="${CXX_FLAGS} -std=c++17 -stdlib=libc++"

before_install:
  - eval "${MATRIX_EVAL}"
  - ./CI/before_install.${TRAVIS_OS_NAME}.sh

install: ./CI/install.${TRAVIS_OS_NAME}.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
